### PR TITLE
More Social Accounts

### PR DESCRIPTION
**Pull request by bcylin**
Added Facebook, Dribbble, and Behance to the contact options. @frozenfung could you please review these changes? Thanks!

```
rake init          # Create me.json
rake remote        # Show the remote name based on the github account in me.json
rake update:info   # Update contact info in me.json
rake update:names  # Update names, job title, and portfolio URL in me.json
```

### CODE REVIEW

**Comment by frozenfung** [comment]
I think that is because hound CI follow the [Ruby style guide](https://github.com/thoughtbot/guides/tree/master/style/ruby) by thoughtbot.
However, in another [guide](https://github.com/bbatsov/ruby-style-guide) maintained by community  thing goes in opposite. It encourages `find` instead of `detect`

related discussion 
https://github.com/houndci/hound/issues/247

And I just do some code tracing with pry:

(console)
$ pry
$ show-method [].detect
resultA
$ show-method [].find
resultB

Boom! 
I just find that resultA and resultB are identical.
so I will consider they twins as a alias to each other.
@bcylin

**Comment by bcylin** [comment]
Thanks @frozenfung, I've updated the `.ruby-style.yml` configuration.

**Comment by bcylin** [comment]
Let's merge this, thanks @frozenfung.

**Comment by frozenfung** [comment]
:8ball:

**Pull request merged**
